<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Akshay-Udhane" failures="1" tests="8" name="Integration Tests" time="0.759" errors="0" timestamp="2025-10-03T15:21:41 IST">
  <testcase classname="tests.IntegrationTest" name="testCompleteDataFlow" time="0.028"/>
  <testcase classname="tests.IntegrationTest" name="testConcurrentOperationsAcrossServices" time="0.011"/>
  <testcase classname="tests.IntegrationTest" name="testDataConsistencyAcrossServices" time="0.007"/>
  <testcase classname="tests.IntegrationTest" name="testErrorPropagationAcrossServices" time="0.003">
    <failure type="java.lang.AssertionError" message="Should return error for invalid node expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Should return error for invalid node expected [true] but found [false]
at tests.IntegrationTest.testErrorPropagationAcrossServices(IntegrationTest.java:177)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testErrorPropagationAcrossServices -->
  <testcase classname="tests.IntegrationTest" name="testPerformanceUnderLoad" time="0.053"/>
  <testcase classname="tests.IntegrationTest" name="testReadWriteCycle" time="0.005"/>
  <testcase classname="tests.IntegrationTest" name="testServiceDiscovery" time="0.088"/>
  <testcase classname="tests.IntegrationTest" name="testServiceRecoveryAfterFailure" time="0.004"/>
</testsuite> <!-- Integration Tests -->
