{"uuid":"559f9cb4-3f06-4a9d-88c4-c759abe831fe","name":"tests.IntegrationTest","children":["e6db3fa3-9d8b-4061-9c64-bd0dffdb684c","eebf7b8b-051b-41bc-a77b-44a732ad9c20","c579c315-bc51-4640-8d9b-f0bfc740576b","e1fc3475-2641-4aa1-b441-bbc7d14195cf","77b7df95-edfc-4ce3-afe5-771e42724488","92c09a1f-b5e2-421c-8b1a-2a725ea65a96","1a7b01b5-8d34-4255-9c11-8051f486719d","98720986-1020-4094-ab8e-b19533184c17","33920f6e-fb8b-41a6-85de-62f09a21d45f"],"befores":[{"name":"setUpRealServiceContext","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Failed to setup real service test context: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use","trace":"java.lang.RuntimeException: Failed to setup real service test context: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use\r\n\tat base.RealServiceTestBase.setUpRealServiceContext(RealServiceTestBase.java:62)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)\r\n\tat org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.access$000(SuiteRunner.java:28)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)\r\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357)\r\n\tat java.base/java.lang.Iterable.forEach(Iterable.java:75)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124)\r\n\tat org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:946)\r\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:594)\r\n\tat org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)\r\n\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)\r\n\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)\r\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:308)\r\n\tat utils.MockBackendServer.start(MockBackendServer.java:29)\r\n\tat base.RealServiceTestBase.setUpRealServiceContext(RealServiceTestBase.java:43)\r\n\t... 21 more\r\nCaused by: org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use\r\n\tat org.springframework.boot.web.server.PortInUseException.lambda$throwIfPortBindingException$0(PortInUseException.java:70)\r\n\tat org.springframework.boot.web.server.PortInUseException.lambda$ifPortBindingException$1(PortInUseException.java:85)\r\n\tat org.springframework.boot.web.server.PortInUseException.ifCausedBy(PortInUseException.java:103)\r\n\tat org.springframework.boot.web.server.PortInUseException.ifPortBindingException(PortInUseException.java:82)\r\n\tat org.springframework.boot.web.server.PortInUseException.throwIfPortBindingException(PortInUseException.java:69)\r\n\tat org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:228)\r\n\tat org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179)\r\n\t... 34 more\r\nCaused by: java.lang.IllegalArgumentException: standardService.connector.startFailed\r\n\tat org.apache.catalina.core.StandardService.addConnector(StandardService.java:235)\r\n\tat org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282)\r\n\tat org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)\r\n\t... 36 more\r\nCaused by: org.apache.catalina.LifecycleException: Protocol handler start failed\r\n\tat org.apache.catalina.connector.Connector.startInternal(Connector.java:1042)\r\n\tat org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)\r\n\tat org.apache.catalina.core.StandardService.addConnector(StandardService.java:232)\r\n\t... 38 more\r\nCaused by: java.net.BindException: Address already in use: bind\r\n\tat java.base/sun.nio.ch.Net.bind0(Native Method)\r\n\tat java.base/sun.nio.ch.Net.bind(Net.java:555)\r\n\tat java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)\r\n\tat java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)\r\n\tat org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:276)\r\n\tat org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:231)\r\n\tat org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1332)\r\n\tat org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1418)\r\n\tat org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:665)\r\n\tat org.apache.catalina.connector.Connector.startInternal(Connector.java:1039)\r\n\t... 40 more\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1759484390926,"stop":1759484391653},{"name":"setUpIntegrationTests","status":"broken","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1759484391659,"stop":1759484391659}],"afters":[{"name":"tearDownRealServiceContext","status":"broken","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1759484391725,"stop":1759484391725}],"start":1759484390926,"stop":1759484391788}