{"uuid":"87aaf761-99e2-4175-a8d7-9303f38e0d25","name":"tests.OpUaConnectionServiceTest","children":["692b6589-21b0-4e1d-a0e7-9a9e14cc0aff","ad941e26-561d-43d0-b800-9e8c6713c3d6","5b525d07-6fe5-4101-a011-8c5285bf318b","9f30948b-8eeb-4b06-a4a5-7d82bf054842","bd712448-249f-4199-823b-fecf6a9229d6","ea39b3f5-a9ee-45a8-a148-3c41bb7a9efa","7d2829c3-90ce-4b69-9aa5-0ec0dbdca4c8","6897cde4-a81b-4d62-af57-80fef63ab479","7d6cce0c-886f-4779-8e3f-7755df731caa"],"befores":[{"name":"setUpRealServiceContext","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Failed to setup real service test context: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use","trace":"java.lang.RuntimeException: Failed to setup real service test context: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use\r\n\tat base.RealServiceTestBase.setUpRealServiceContext(RealServiceTestBase.java:62)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)\r\n\tat org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.access$000(SuiteRunner.java:28)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)\r\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357)\r\n\tat java.base/java.lang.Iterable.forEach(Iterable.java:75)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124)\r\n\tat org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:946)\r\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:594)\r\n\tat org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)\r\n\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)\r\n\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)\r\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:308)\r\n\tat utils.MockBackendServer.start(MockBackendServer.java:29)\r\n\tat base.RealServiceTestBase.setUpRealServiceContext(RealServiceTestBase.java:43)\r\n\t... 21 more\r\nCaused by: org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use\r\n\tat org.springframework.boot.web.server.PortInUseException.lambda$throwIfPortBindingException$0(PortInUseException.java:70)\r\n\tat org.springframework.boot.web.server.PortInUseException.lambda$ifPortBindingException$1(PortInUseException.java:85)\r\n\tat org.springframework.boot.web.server.PortInUseException.ifCausedBy(PortInUseException.java:103)\r\n\tat org.springframework.boot.web.server.PortInUseException.ifPortBindingException(PortInUseException.java:82)\r\n\tat org.springframework.boot.web.server.PortInUseException.throwIfPortBindingException(PortInUseException.java:69)\r\n\tat org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:228)\r\n\tat org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179)\r\n\t... 34 more\r\nCaused by: java.lang.IllegalArgumentException: standardService.connector.startFailed\r\n\tat org.apache.catalina.core.StandardService.addConnector(StandardService.java:235)\r\n\tat org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282)\r\n\tat org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)\r\n\t... 36 more\r\nCaused by: org.apache.catalina.LifecycleException: Protocol handler start failed\r\n\tat org.apache.catalina.connector.Connector.startInternal(Connector.java:1042)\r\n\tat org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)\r\n\tat org.apache.catalina.core.StandardService.addConnector(StandardService.java:232)\r\n\t... 38 more\r\nCaused by: java.net.BindException: Address already in use: bind\r\n\tat java.base/sun.nio.ch.Net.bind0(Native Method)\r\n\tat java.base/sun.nio.ch.Net.bind(Net.java:555)\r\n\tat java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)\r\n\tat java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)\r\n\tat org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:276)\r\n\tat org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:231)\r\n\tat org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1332)\r\n\tat org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1418)\r\n\tat org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:665)\r\n\tat org.apache.catalina.connector.Connector.startInternal(Connector.java:1039)\r\n\t... 40 more\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1759484484781,"stop":1759484485491},{"name":"setUpOpUaTests","status":"broken","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1759484485662,"stop":1759484485662}],"afters":[{"name":"tearDownRealServiceContext","status":"broken","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1759484485811,"stop":1759484485811}],"start":1759484484771,"stop":1759484486310}