{"uuid":"957bb8dd-f86b-4bae-a06b-e5823685775d","name":"tests.IntegrationTest","children":["c028d3f8-7e35-49bf-9cf3-85a4e9f4b634","990472ea-2445-4411-8071-8f5bcd5dff81","04644d97-4879-4cec-bf48-ccc9a55a4b12","14923f0a-2aaa-4b8c-922c-f9218ea2a4f4","ccf9a412-ec91-4e62-a2b0-2db41b546292","baab60d7-98b0-48f7-bcdc-91ad3a3ec873","a83eef5b-a5d2-42eb-aadd-1930cb3a1883","c2df9410-590d-4936-b188-7a95b0a70591","65064b51-a08c-4d8b-80fd-ea00c085da58"],"befores":[{"name":"setUpRealServiceContext","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Failed to setup real service test context: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use","trace":"java.lang.RuntimeException: Failed to setup real service test context: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use\r\n\tat base.RealServiceTestBase.setUpRealServiceContext(RealServiceTestBase.java:62)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)\r\n\tat org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.access$000(SuiteRunner.java:28)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)\r\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357)\r\n\tat java.base/java.lang.Iterable.forEach(Iterable.java:75)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124)\r\n\tat org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:946)\r\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:594)\r\n\tat org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)\r\n\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)\r\n\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)\r\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:308)\r\n\tat utils.MockBackendServer.start(MockBackendServer.java:29)\r\n\tat base.RealServiceTestBase.setUpRealServiceContext(RealServiceTestBase.java:43)\r\n\t... 21 more\r\nCaused by: org.springframework.boot.web.server.PortInUseException: Port 8085 is already in use\r\n\tat org.springframework.boot.web.server.PortInUseException.lambda$throwIfPortBindingException$0(PortInUseException.java:70)\r\n\tat org.springframework.boot.web.server.PortInUseException.lambda$ifPortBindingException$1(PortInUseException.java:85)\r\n\tat org.springframework.boot.web.server.PortInUseException.ifCausedBy(PortInUseException.java:103)\r\n\tat org.springframework.boot.web.server.PortInUseException.ifPortBindingException(PortInUseException.java:82)\r\n\tat org.springframework.boot.web.server.PortInUseException.throwIfPortBindingException(PortInUseException.java:69)\r\n\tat org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:228)\r\n\tat org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43)\r\n\tat org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179)\r\n\t... 34 more\r\nCaused by: java.lang.IllegalArgumentException: standardService.connector.startFailed\r\n\tat org.apache.catalina.core.StandardService.addConnector(StandardService.java:235)\r\n\tat org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282)\r\n\tat org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)\r\n\t... 36 more\r\nCaused by: org.apache.catalina.LifecycleException: Protocol handler start failed\r\n\tat org.apache.catalina.connector.Connector.startInternal(Connector.java:1042)\r\n\tat org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)\r\n\tat org.apache.catalina.core.StandardService.addConnector(StandardService.java:232)\r\n\t... 38 more\r\nCaused by: java.net.BindException: Address already in use: bind\r\n\tat java.base/sun.nio.ch.Net.bind0(Native Method)\r\n\tat java.base/sun.nio.ch.Net.bind(Net.java:555)\r\n\tat java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)\r\n\tat java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)\r\n\tat org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:276)\r\n\tat org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:231)\r\n\tat org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1332)\r\n\tat org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1418)\r\n\tat org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:665)\r\n\tat org.apache.catalina.connector.Connector.startInternal(Connector.java:1039)\r\n\t... 40 more\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1759484486314,"stop":1759484487017},{"name":"setUpIntegrationTests","status":"broken","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1759484487020,"stop":1759484487020}],"afters":[{"name":"tearDownRealServiceContext","status":"broken","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1759484487080,"stop":1759484487080}],"start":1759484486314,"stop":1759484487135}